# Generated by Django 4.0 on 2021-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='名無しのマッチョ', max_length=50, verbose_name='投稿者')),
                ('text', models.TextField(max_length=500, verbose_name='コメント')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
            ],
        ),
    ]
